### ISSUE TITLE
Image "fullness" control

### ISSUE THREAD

**Issue by owang** [YontiLevin/Embeddings2Image#1]
When embedding my images I am left with a huge canvas with sparse tiny images. Changing the image size parameter does not increase the density of images, as the final resolution increases as well. Do you know which parameters control how "dense" the output canvas is? I would like to have large images relative to the total canvas size.  Thanks!

**Comment by YontiLevin** [comment]
you can try to change the 'each_img_size' parameter

**Comment by YontiLevin** [comment]
i updated the project. now you should be able to use each_img_size to enlarge the images
