### ISSUE TITLE
Row/column indexing error?

### ISSUE THREAD

**Issue by owang** [YontiLevin/Embeddings2Image#2]
When running this code, I get the following error:

```
 File "./visualize-tsne/modules.py", line 267, in _scatter
    image[x0 + dx:x0 + dx + x1, y0 + dy:y0 + dy + y1] = small_img
ValueError: could not broadcast input array from shape (80,65,3) into shape (65,80,3)
```

This can be fixed by adding the following line:
```
if np.max(image[x0 + dx:x0 + dx + x1, y0 + dy:y0 + dy + y1]) > 0:
  continue
--> small_img = small_img.transpose(1,0,2)
image[x0 + dx:x0 + dx + x1, y0 + dy:y0 + dy + y1] = small_img
```
But then the images are all rotated 90 degrees. 

Simply switching the indices lead to some other issues.

**Comment by YontiLevin** [comment]
I returned to the code last week as i wanted to add UMAP projections and found out a few bugs that i'm now fixing. I'll look into that too. Hopefully I'll have time to push an improved version this week.

**Comment by YontiLevin** [comment]
meanwhile
try changing line 251 to
`image = np.zeros((self.output_img_size + self.each_img_size, self.output_img_size + self.each_img_size, 3)) * self.background_color`
that should solve it

**Comment by YontiLevin** [comment]
project updated
