### ISSUE TITLE
row, column index error

### ISSUE THREAD

**Issue by ChloeEHKim** [YontiLevin/Embeddings2Image#4]
Hi
Thank you for your work. This saved me a lot of time!

I faced the same problem with one of the previous issues. The shape of the small_img doesn't match with the row, column indexing. 
--------------------------------------------------------------------
File "./visualize-tsne/modules.py", line 267, in _scatter
    image[x0 + dx:x0 + dx + x1, y0 + dy:y0 + dy + y1] = small_img
ValueError: could not broadcast input array from shape (100,75,3) into shape (75,100,3)
This can be fixed by adding the following line:
--------------------------------------------------------------------
I found out the indexing has to be changed like this. 
image[x0 + dx:x0 + dx + x1, y0 + dy:y0 + dy + y1] = small_img
--> image[ y0 + dy:y0 + dy + y1, x0 + dx:x0 + dx + x1] = small_img

If you could update the code, it would be great!

**Comment by YontiLevin** [comment]
thanks
hopefully, it will be fixed in a couple of hours

**Comment by YontiLevin** [comment]
fixed, pushed and updated on pypi
please check it and reopen the issue if still doesn't work
