### ISSUE TITLE
End to end example

### ISSUE THREAD

**Issue by nivha** [YontiLevin/Embeddings2Image#5]
Great project! Adding an end to end example would be very helpful.
(for example, the mnist example, but adding how the data was created and so on)

(also, there are hard-coded paths in the code, such as in modules.py line 165)

**Comment by YontiLevin** [comment]
Thanks!

It might take me a while as Im a bit busy lately.
I will keep this issue open to remind me.

**Comment by nivha** [comment]
I actually kinda debugged part of the code

**Comment by nivha** [comment]
accidentay closed..

**Comment by YontiLevin** [comment]
if you already improved the code then please open a pull request
lets try to push that in for others

**Comment by nivha** [comment]
there you go, added here https://github.com/YontiLevin/Embeddings2Image/pull/6

**Comment by YontiLevin** [comment]
thanks
PR was approved and merged
